AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an IAM role'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: DOC-EXAMPLE-BUCKET