AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Sample Template for creating EC2 instance
Parameters:
  CFNUsers: SampleS3WritePolicy
Resources:
  S3Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Ref CFNUsers
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:Describe*'
              - 'cloudformation:List*'
              - 'cloudformation:Get*'
            Resource: '*'